backend:
  name: github
  repo: wearesideways/sw-site
  branch: master
  api_root: https://api.github.com
  base_url: https://sideways.pages.dev
  auth_endpoint: /api/auth
media_folder: public/images
public_folder: /images

collections:
  - name: 'config'
    label: 'Config'
    delete: false
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Config'
        file: 'config.json'
        description: 'General site settings'
        fields:
          - label: 'URL'
            name: 'base_url'
            widget: 'string'
            hint: 'Do not enter the trailing slash of the URL'
          - label: 'Site title'
            name: 'site_title'
            widget: 'string'
          - label: 'Site description'
            name: 'site_description'
            widget: 'string'
          - label: 'Site keywords'
            name: 'site_keywords'
            widget: 'list'
            summary: '{{fields.keyword.keyword}}'
            field:
              label: Keyword
              name: keyword
              widget: 'string'
          - label: 'Twitter account'
            name: 'twitter_account'
            widget: 'string'
          - label: 'GitHub account'
            name: 'github_account'
            widget: 'string'

  - name: 'meta'
    label: 'Meta'
    delete: false
    editor:
      preview: false
    files:
      - name: 'authors'
        label: 'Authors'
        file: 'meta/authors.yml'
        description: 'Author descriptions'
        fields:
          - name: authors
            label: Authors
            label_singular: 'Author'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of a URL identifies the author'
              - label: 'Name'
                name: 'name'
                widget: 'string'
                hint: 'First and Last'
              - label: 'Introduction'
                name: 'introduction'
                widget: 'text'
      - name: 'tags'
        label: 'Tags'
        file: 'meta/tags.yml'
        description: 'List of tags'
        fields:
          - name: tags
            label: Tags
            label_singular: 'Tag'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of a URL identifies the tag'
              - label: 'Display Name'
                name: 'name'
                widget: 'string'
                hint: 'Tag name for displaying on the site'
      - name: 'modules'
        label: 'Modules'
        file: 'meta/modules.yml'
        description: 'List of modules'
        fields:
          - name: modules
            label: Modules
            label_singular: 'Module'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of the page identifies the module'
              - label: 'Display Name'
                name: 'name'
                widget: 'string'
                hint: 'Module name for displaying on the site'

  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts/'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        date_format: 'YYYY-MM-DD'
        time_format: false
      - label: Author
        name: 'author'
        widget: relation
        collection: 'meta'
        file: 'authors'
        search_fields:
          - 'authors.*.name'
        display_fields:
          - 'authors.*.name'
        value_field: 'authors.*.slug'
      - label: Tags
        label_singular: 'Tag'
        name: 'tags'
        widget: list
        summary: '{{fields.tag}}'
        field:
          label: Tag
          name: tag
          widget: relation
          collection: 'meta'
          file: 'tags'
          search_fields:
            - 'tags.*.name'
          display_fields:
            - 'tags.*.name'
          value_field: 'tags.*.slug'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages/'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        date_format: 'YYYY-MM-DD'
        time_format: false
      - label: Author
        name: 'author'
        widget: relation
        collection: 'meta'
        file: 'authors'
        search_fields:
          - 'authors.*.name'
        display_fields:
          - 'authors.*.name'
        value_field: 'authors.*.slug'
      - label: Modules
        label_singular: 'Module'
        name: 'modules'
        widget: list
        summary: '{{fields.module}}'
        field:
          label: Module
          name: module
          widget: relation
          collection: 'meta'
          file: 'modules'
          search_fields:
            - 'modules.*.name'
          display_fields:
            - 'modules.*.name'
          value_field: 'modules.*.slug'

  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects/'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        date_format: 'YYYY-MM-DD'
        time_format: false
      - label: Author
        name: 'author'
        widget: relation
        collection: 'meta'
        file: 'authors'
        search_fields:
          - 'authors.*.name'
        display_fields:
          - 'authors.*.name'
        value_field: 'authors.*.slug'
      - label: Tags
        label_singular: 'Tag'
        name: 'tags'
        widget: list
        summary: '{{fields.tag}}'
        field:
          label: Tag
          name: tag
          widget: relation
          collection: 'meta'
          file: 'tags'
          search_fields:
            - 'tags.*.name'
          display_fields:
            - 'tags.*.name'
          value_field: 'tags.*.slug'
      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'string'
      - label: 'Featured Image'
        name: 'thumbnail'
        widget: 'image'
        choose_url: true
        default: '/uploads/placeholder.jpg'
        media_library:
          config:
            multiple: true
      - label: 'Content'
        name: 'content'
        widget: 'markdown'
